### ISSUE TITLE
Gnome Style Guidelines

### ISSUE THREAD

**Issue by superdachs** [vchlum/wireless-hid#1]
Hi,

I think the coloring of the Widget is not compatible with the Guidelines for Gnome. It looks bad when only the mouse and keyboard icon are colored. Would it eventually be possible to show the icon in white, like other bar icons, and only make it red when the battery is low? Another idea I had was to show the battry by having the icon filling from the bottom with lighter white than the background of the icon to show a level like battery indicators do.

**Comment by vchlum** [comment]
Hi @superdachs! The current color-rules are:
 * green is for 100-30%
 * orange is for 30-10%
 * red is for 10-0%

I agree that the green can be removed. Should we preserve the orange?

**Comment by vchlum** [comment]
Green colorization is removed. I consider the orange and red still useful, and I believe it will follow the gnome style now. Resolved.
