### ISSUE TITLE
Battery levels reported as -1%

### ISSUE THREAD

**Issue by dirusulixes** [vchlum/wireless-hid#10]
on arch linux with the latest gnome packages installed since a few days ago the indicators always report -1% battery levels and keyboard icons.  The hid devices are a keyboard and a mouse paired with the same logitech unifying receiver (in case it matters). Power levels are read correctly in the settings.
![Screenshot from 2022-05-19 14-20-01](https://user-images.githubusercontent.com/5693623/169303636-bdbf4d26-f1b5-4c9c-bbc3-29cf0c4a8958.png)
![Screenshot from 2022-05-19 14-20-17](https://user-images.githubusercontent.com/5693623/169303686-456bdcfc-fdef-49ce-a3b3-35491a60849e.png)

**Comment by Baiyah7o** [comment]
Sam here with, bluetooth device is reported by `upower -d` correctly but is shown with -1%.
```
Device: /org/freedesktop/UPower/devices/mouse_dev_F8_B3_C7_CD_6F_14
  native-path:          /org/bluez/hci0/dev_F8_B3_C7_CD_6F_14
  model:                DA V2 Pro
  serial:               F8:B3:C7:CD:6F:14
  power supply:         no
  updated:              Fr 20 Mai 2022 16:39:28 CEST (20 seconds ago)
  has history:          yes
  has statistics:       no
  mouse
    present:             yes
    rechargeable:        no
    state:               unknown
    warning-level:       none
    percentage:          93%
    icon-name:          'battery-missing-symbolic'
```
![Screenshot from 2022-05-20 16-43-06](https://user-images.githubusercontent.com/75333882/169552890-0af1ae1a-f244-4b14-9ab1-e17c21690be0.png)

**Comment by keithy999** [comment]
Same for me with 2 different Bluetooth keyboards running on Arch, Upower reports correctly

Thanks

**Comment by vchlum** [comment]
Thank you for reporting. I will look into it. What is the gnome-shell version, please?

**Comment by keithy999** [comment]
I'm on 42.1

HTH

**Comment by AlexWayfer** [comment]
I have only a mouse, Logitech G603, but got a keyboard (red) icon.

GNOME Shell version is 42.1-1 (on Arch).

**Comment by stuarthayhurst** [comment]
Same issue on Debian Sid, device looks fine running `upower -d`. I also noticed my Logitech G502 mouse is showing as a keyboard, which started at the same time as this problem
GNOME Shell: `42.1`
Extension version: `5`
Upower version (client + daemon): `0.99.18`

**Comment by vchlum** [comment]
There is a new version of upower on your systems. The extension is fixed by removing unnecessary sync... A new version is coming soon, but first... Please @dirusulixes, @stuarthayhurst, or @AlexWayfer check the command `upower -d` for the device type. I believe the wrong type is in upower. Could you confirm?

**Comment by stuarthayhurst** [comment]
```
Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                G502 LIGHTSPEED Wireless Gaming Mouse
  serial:               
  power supply:         no
  updated:              Sun 22 May 2022 09:20:53 BST (0 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    percentage:          89%
    icon-name:          'battery-missing-symbolic'
```

I assume there shouldn't be a section on keyboard for a mouse?

**Comment by dirusulixes** [comment]
```
Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                MX Vertical Advanced Ergonomic Mouse
  serial:               407b-8c-11-1d-5c
  power supply:         no
  updated:              Sun 22 May 2022 10:49:29 BST (17 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    battery-level:       unknown
    percentage:          50% (should be ignored)
    icon-name:          'battery-missing-symbolic'

Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_1
  native-path:          hidpp_battery_1
  model:                Wireless Touch Keyboard K400
  serial:               400e-13-e3-0d-2d
  power supply:         no
  updated:              Sun 22 May 2022 10:49:43 BST (3 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'
```

Yes, seems to be a problem with upower

**Comment by stuarthayhurst** [comment]
This seems to be reported upstream already [here](https://gitlab.freedesktop.org/upower/upower/-/issues/189)

**Comment by AlexWayfer** [comment]
> check the command `upower -d` for the device type. I believe the wrong type is in upower. Could you confirm?

Yes, "keyboard".

**Comment by vchlum** [comment]
fixed, new verison released
