### ISSUE TITLE
[Feature Request] Support for Razer peripherals

### ISSUE THREAD

**Issue by Aasikki** [vchlum/wireless-hid#14]
Awesome, extension for my bluetooth keyboard and xbox controller! Unfortunately my mouse doesn't seem to be supported. Would it be possible to also add support for Razer peripherals? There already exists a [project](https://github.com/HoroTW/RazerBatteryTray) which leverages [OpenRazer](https://github.com/openrazer/openrazer) for that, but unfortunately I can't get it working on fedora 37 currently and it would be nice to have everything in the same place.

**Comment by vchlum** [comment]
This extension only shows the same devices as `upower -d`. The cleanest way to add support for another device is through the [upower project](https://upower.freedesktop.org/).
