### ISSUE TITLE
Extension not completely cleaning up after being disabled

### ISSUE THREAD

**Issue by stuarthayhurst** [vchlum/wireless-hid#24]
I've noticed the following errors in the logs recently:

```
Jun 03 15:14:41 snakeroot gnome-shell[8464]: Object St.Label (0x55b128808550), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jun 03 15:14:41 snakeroot gnome-shell[8464]: == Stack trace for context 0x55b124cd8f00 ==
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #0   55b12633de28 i   /home/ratus5/.local/share/gnome-shell/extensions/wireless-hid@chlumskyvaclav.gmail.com/wirelesshid.js:171 (36c70e13d650 @ 76)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #1   55b12633dd90 i   /home/ratus5/.local/share/gnome-shell/extensions/wireless-hid@chlumskyvaclav.gmail.com/wirelesshid.js:196 (36c70e185f60 @ 17)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #2   55b12633dce8 i   /home/ratus5/.local/share/gnome-shell/extensions/wireless-hid@chlumskyvaclav.gmail.com/wirelesshid.js:192 (36c70e15af10 @ 195)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #3   7ffc9186c410 b   self-hosted:1121 (bf9a0373f60 @ 501)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: == Stack trace for context 0x55b124cd8f00 ==
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #0   55b12633dd90 i   /home/ratus5/.local/share/gnome-shell/extensions/wireless-hid@chlumskyvaclav.gmail.com/wirelesshid.js:199 (36c70e185f60 @ 64)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #1   55b12633dce8 i   /home/ratus5/.local/share/gnome-shell/extensions/wireless-hid@chlumskyvaclav.gmail.com/wirelesshid.js:192 (36c70e15af10 @ 195)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: #2   7ffc9186c410 b   self-hosted:1121 (bf9a0373f60 @ 501)
Jun 03 15:14:41 snakeroot gnome-shell[8464]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 03 15:14:41 snakeroot gnome-shell[8464]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 03 15:14:41 snakeroot gnome-shell[8464]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 03 15:14:41 snakeroot gnome-shell[8464]: Object St.Icon (0x55b125f624e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

This only appears after the extension has been unloaded, and occurs exactly every 30 seconds after this happens. My guess is that this is the callback on the signal for UPower updating the battery information is still being called, as the extension hasn't unloaded properly. It then tries to update the label and icon, which no longer exist, as those have been cleaned up by the shell.

I'm running the latest git version, from a clean boot, in case it was a bug from the previous version carrying through until a reboot.

I tried sorting this myself, but I can't follow the logic the code uses to clean up, as I can't seem to understand when `_onDestroy()` would be called on the `WirelessHID` class. Perhaps it's not being called, and the function should also call `clean()` on each device?

**Comment by stuarthayhurst** [comment]
It seems this still happens when the extension hasn't been unloaded, so I guess it's related to individual devices not cleaning up when 'destroyed' (in quotes as I'm not sure they are being properly destroyed).

**Comment by stuarthayhurst** [comment]
Did some investigating, it turned out that `destroy()` was never called on the devices. So none of the settings disconnected, and upower's 30 second update interval was causing deleted objects to be accessed, as predicted.

#26 should close this :)

**Comment by vchlum** [comment]
Hi @stuarthayhurst ! I appreciate your help. I have been busy. New version  will be released soon. Thanks for the fix again.
