### ISSUE TITLE
Option to disconnect bluetooth devices 

### ISSUE THREAD

**Issue by valters-tomsons** [vchlum/wireless-hid#3]
Hi, awesome extension!

Would it be possible to support disconnecting Bluetooth devices by clicking on the in the drop-down menu?

**Comment by vchlum** [comment]
Hi! Sorry for the long silence. Thank you for the idea. From what I know and checked, it would probably require additional dependencies like bluez or something. I prefer zero dependency extension. I will keep this idea in my mind, but I do not intend to add it now.
