### ISSUE TITLE
Logitech HID++/Bluetooth devices are detected twice with different info

### ISSUE THREAD

**Issue by armonge** [vchlum/wireless-hid#33]
As described here https://gitlab.freedesktop.org/upower/upower/-/issues/166 some devices are detected twice by upower due to an underlying kernel behavior related to some HID++ logitech driver, this therefore makes it so those devices are displayed twice in wireless-hid

The solution proposed to upower was to deduplicate those devices using the device serial number, but seems like for now that proposal was rejected. I believe we could do that deduplication instead in the gnome-shell extension.

I could send a PR with this, would such a contribution be accepted?

**Comment by stuarthayhurst** [comment]
Wasn't this sorted with https://gitlab.freedesktop.org/upower/upower/-/merge_requests/166?

If you're having issues with duplicate entries with the latest version of UPower, I'd recommend filing an issue upstream, as then everyone that uses UPower benefits, and it's one less workaround needed in this project.

**Comment by armonge** [comment]
I can confirm that indeed the issue is solved by updating to latest upower. Thanks a lot for checking it out, seems my search or understanding of that issue wasn't the best. For anyone in Ubuntu like me, you can update to the latest upower with the packages found in [Launchpad](https://launchpad.net/ubuntu/+source/upower/1.90.2-4)
