### ISSUE TITLE
HyperX Cloud Alpha Wireless not detected

### ISSUE THREAD

**Issue by moritzbindewald** [vchlum/wireless-hid#35]
Hey, the HyperX Cloud Alpha Wireless seems to no get detected. https://github.com/Sapd/HeadsetControl Is able to detect and control this headset. Would be greatly appreciated, if someone could make this work. Thx!

**Comment by stuarthayhurst** [comment]
Hi, can you post the output of `upower -d` please?

This extension can only show devices detected by `upower`. `upower` can only show devices that are managed by the kernel / bluetooth stack. If HeadsetControl can control the device, it's possible to write a driver, someone just needs to do it. Sadly, that's way out of scope for this project.

**Comment by stuarthayhurst** [comment]
Closing, since there's no driver for this headset in the kernel, so this project can't really support it
