### ISSUE TITLE
Different values for icon colours

### ISSUE THREAD

**Issue by stuarthayhurst** [vchlum/wireless-hid#39]
Currently, we have orange for low battery at 30%, and red for critical at 10%, however UPower uses 20% and 5% respectively, so the extension changing colours and the notifications sent by the shell don't line up.

@vchlum If you'd rather the values line up with upstream, I'd be happy to change it, otherwise I'll leave it and close this :)

**Comment by vchlum** [comment]
The change to 20% and 5% is a good idea. Thank you @stuarthayhurst !
