### ISSUE TITLE
Refresh interval?

### ISSUE THREAD

**Issue by tecnobrat** [vchlum/wireless-hid#4]
I've noticed that while upower and Gnome's settings app show my keyboard (MX Keys) is now at 50% power, the gnome extension doesn't see that yet. Is there some sort of refresh interval?

**Comment by vchlum** [comment]
Hi @tecnobrat! There is not a refresh interval. It should update immediately. I will investigate. Thank you.

**Comment by valters-tomsons** [comment]
My Dualshock 4 controllers also do not get refreshed.

**Comment by vchlum** [comment]
Fixed. Sorry for the long silence. The new version will be available soon.

**Comment by tecnobrat** [comment]
I can confirm the new version fixes the bug, thank you very much!
