### ISSUE TITLE
GNOME 46: Apple Magic Trackpad always shows 0% or 100%

### ISSUE THREAD

**Issue by TriVoxel** [vchlum/wireless-hid#44]
This extension used to work on GNOME 45, but on Fedora 40 Atomic with GNOME 46 desktop, I have only ever seen it report as 0% or 100% at all times. Also, if I plug it in with a cable, I usually see two devices, one for the Bluetooth, one for the wire. It seems to show the battery level correctly if I have it plugged in.

Other devices seem to work. I have some wireless game controllers that work, when I plug in my iPhone, it tells me the charge somehow. Not my Apple Magic Trackpad though.

[This is the product I'm using.](https://www.apple.com/shop/product/MMMP3AM/A/)

_Side note: I can highly recommend this product to any GNOME user, it is fantastic on Linux, especially for gestures!_

Additional information:

This may be unrelated but, if I enable my 2007 Apple Mighty mouse at the same time, the Magic Trackpad disappears from the menu for some reason, but works just fine regardless. The battery indicator works on the Mighty Mouse, btw.

**Comment by stuarthayhurst** [comment]
Can you post the output of `upower -d` when on Bluetooth, and again when plugged in too? And once more when the mighty mouse is connected too?

This is probably a bug in `UPower`, since we just display whatever the daemon comes up with, so it may have regressed when you updated.

**Comment by TriVoxel** [comment]
## Bluetooth

```
Device: /org/freedesktop/UPower/devices/battery_hid_08o65o18ob8o59o25_battery
  native-path:          hid-08:65:18:b8:59:25-battery
  model:                Magic Trackpad
  serial:               08:65:18:b8:59:25
  power supply:         no
  updated:              Wed 31 Dec 1969 05:00:00 PM MST (1717465374 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    percentage:          0%
    icon-name:          'battery-missing-symbolic'
  History (charge):
    1717465374	0.000	unknown
  History (rate):
    1717465374	0.000	unknown
```

## Bluetooth & Wired

```
Device: /org/freedesktop/UPower/devices/battery_hid_08o65o18ob8o59o25_battery
  native-path:          hid-08:65:18:b8:59:25-battery
  model:                Magic Trackpad
  serial:               08:65:18:b8:59:25
  power supply:         no
  updated:              Mon 03 Jun 2024 07:45:24 PM MDT (9 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    percentage:          100%
    icon-name:          'battery-full-charged-symbolic'
  History (charge):
    1717465524	100.000	fully-charged
    1717465524	0.000	unknown
  History (rate):
    1717465524	0.000	unknown

Device: /org/freedesktop/UPower/devices/battery_hid_CC22423008T1F42AN_battery
  native-path:          hid-CC22423008T1F42AN-battery
  model:                Apple Inc. Magic Trackpad
  serial:               CC22423008T1F42AN
  power supply:         no
  updated:              Mon 03 Jun 2024 07:45:25 PM MDT (8 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    percentage:          100%
    icon-name:          'battery-full-charged-symbolic'
  History (charge):
    1717465525	100.000	fully-charged
    1717465525	0.000	unknown
  History (rate):
    1717465525	0.000	unknown
```

_Note: The Bluetooth disconnects when wired, but upower still shows the wireless device_

## Bluetooth w/ Mighty Mouse

```
Device: /org/freedesktop/UPower/devices/battery_hid_08o65o18ob8o59o25_battery
  native-path:          hid-08:65:18:b8:59:25-battery
  model:                Magic Trackpad
  serial:               08:65:18:b8:59:25
  power supply:         no
  updated:              Mon 03 Jun 2024 07:50:40 PM MDT (6 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    percentage:          100%
    icon-name:          'battery-full-charged-symbolic'
  History (charge):
    1717465840	100.000	unknown
    1717465840	0.000	unknown
    1717465810	100.000	fully-charged
    1717465810	0.000	unknown
    1717465780	100.000	fully-charged
    1717465780	0.000	unknown
    1717465750	100.000	fully-charged
    1717465750	0.000	unknown
    1717465734	100.000	fully-charged
    1717465734	0.000	unknown
  History (rate):
    1717465840	0.000	unknown
    1717465810	0.000	unknown
    1717465780	0.000	unknown
    1717465750	0.000	unknown
    1717465734	0.000	unknown

Device: /org/freedesktop/UPower/devices/battery_hid_00o23o6coc2o4fob5_battery
  native-path:          hid-00:23:6c:c2:4f:b5-battery
  model:                Mighty Mouse
  serial:               08:65:18:b8:59:25
  power supply:         no
  updated:              Mon 03 Jun 2024 07:50:39 PM MDT (7 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          71%
    icon-name:          'battery-full-symbolic'
  History (charge):
    1717465846	0.000	unknown
  History (rate):
    1717465846	0.000	unknown
```

## Additional notes

So, when the device was initially turned on, it read as 0% and, ever since plugging it in to test, it has started displaying 100%. It also doesn't disappear from upower anymore when disconnected, which is odd. It probably is at 100% now, but I doubt it will show anything but once it discharges, other than 0%.

**Comment by stuarthayhurst** [comment]
Thanks, it seems this extension is behaving correctly then, UPower probably needs some reports upstream to fix these then. I know there's some code to de-duplicate Logitech wired + wireless devices, your hardware probably needs a similar fix, although it might struggle since the serial number is different between wired and wireless.

Bluetooth support for battery reporting is also experimental if I remember correctly, so the Bluetooth stack might also be going wrong, not sure where to report that.

**Comment by stuarthayhurst** [comment]
Closing, since this seems to be an upstream issue. Feel free to reopen if the output of `upower -d` and what the extension shows doesn't match at any point :)
