### ISSUE TITLE
Using the warning-level from UPower in case of devices that don't report it, leads to lack of reporting low and critical states in extension

### ISSUE THREAD

**Issue by Xev** [vchlum/wireless-hid#48]
```
Device: /org/freedesktop/UPower/devices/headset_dev_38_18_4C_D4_C6_50
  native-path:          /org/bluez/hci0/dev_38_18_4C_D4_C6_50
  model:                WH-1000XM3
  serial:               38:18:4C:D4:C6:50
  power supply:         no
  updated:              pią, 9 sie 2024, 06:55:40 (12 seconds ago)
  has history:          yes
  has statistics:       no
  headset
    warning-level:       none
    percentage:          10%
    icon-name:          'battery-missing-symbolic'
```
This headset does not report warning-level so `if (this.device.warning_level === UPowerGlib.DeviceLevel.CRITICAL) {` won't work.

I assume there must be more devices that don't report _warning-level_ even if they know _percentage_, so in such case I think the best solution would be to add toggle and two value inputs in config of extension for ignoring _warning-level_ of devices and _percentages_ for battery to be considered in low or critical state. By default toggle set to _false_, so that it follows _warning-level_ from _upower_ and in rare cases like mine user would be able to set it to _true_ and set own thresholds.

I obviously would have preferred to interfere with upower and add behavior of setting warning-level for my headset, but I didn't find any materials how to do it, and only information I have found pointed to it being not possible. Hence the issue report. For now I just modify js file, but "fixing" it with each update is tedious.

**Comment by stuarthayhurst** [comment]
Oh that's annoying, I thought upower handled missing warning levels already. What happens if you use `this.device.warning_level === UPowerGlib.DeviceLevel.UNKNOWN`? If that matches we can probably just check for that and fall back to extension-configured limits.

**Comment by Xev** [comment]
```
_getColorEffect() {
        let color;
        if (this.device.warning_level === UPowerGlib.DeviceLevel.UNKNOWN) {
            color = Clutter.Color.new(0, 255, 0, 255);
        } else if (this.device.percentage <= 20) {
            color = Clutter.Color.new(255, 0, 0, 255);
        } else if (this.device.percentage <= 50) {
            color = Clutter.Color.new(255, 165, 0, 255);
        } else {
            return null;
        }

        return Clutter.ColorizeEffect.new(color);
    }
```
to test I have it modified to this, sadly after restart it did not become green, meaning UPower indeed annoyingly does not provide information that it is missing warning level
```
upower -v
UPower client version 1.90.4
UPower daemon version 1.90.4
```
I am using the newest version from arch repo.

**Comment by stuarthayhurst** [comment]
Thanks for testing, I guess I can throw the feature behind a setting then, and default to not using warning levels to keep it working for the largest number of people

**Comment by stuarthayhurst** [comment]
@Xev Could you test https://github.com/stuarthayhurst/wireless-hid/tree/fix-warning-levels please?

**Comment by Xev** [comment]
Works as intended.

To test I have only modified line with if to 90% from 20%, and now whenever I toggle _use device reported warning level_, icon does switch between white and orange as intended.
