### ISSUE TITLE
[RFE] Include the % in the bar itself

### ISSUE THREAD

**Issue by e-minguez** [vchlum/wireless-hid#5]
Currently in order to check the %, you need to click on the extension icon and I think it would be nice if the battery is shown in the bar itself instead.

**Comment by vchlum** [comment]
Sorry, I do not intend to do so. It would be acceptable with only one device connected. With three or even more devices, the bar would be too long :( I also believe the orange and red color indicates that the battery will die soon in the bar, which is sufficient.
