### ISSUE TITLE
Empty hover when no devices are connected

### ISSUE THREAD

**Issue by SuperSamus** [vchlum/wireless-hid#7]
If no wireless device is connected, the empty icon can still be hovered by the cursor (left part of the image):
![image](https://user-images.githubusercontent.com/40663462/147556757-e65d079a-0f7d-45d6-99b4-6821c956084b.png)
If no devices are connected there should be nothing at all, like in [Removable Drive Menu](https://extensions.gnome.org/extension/7/removable-drive-menu/).

**Comment by vchlum** [comment]
Thank you @SuperSamus for reporting. Fixed. Version 4 should be available soon.
